{
 "title": "Docker Container & Host Metrics",
 "description": "A simple overview of the most important Docker host and container metrics. (cAdvisor/Prometheus)",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(container_last_seen{id=~\"/docker/[a-f0-9]+\"}, job)"
   },
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(container_last_seen{job=~\"$job\"}, instance)"
   },
   {
    "name": "port",
    "label": "Port",
    "query": "label_values(container_last_seen{instance=~\"$node.*\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Running containers",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(container_last_seen{id=~\"/docker/[a-f0-9]+\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "CPU Usage on Node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total[$interval])) * 100",
     "legendFormat": "host"
    }
   ]
  },
  {
   "title": "Free and Used Disk Space on Node",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{fstype=~\"ext4|xfs|tmpfs\"}",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "node_filesystem_size_bytes{fstype=~\"ext4|xfs|tmpfs\"} - node_filesystem_avail_bytes{fstype=~\"ext4|xfs|tmpfs\"}",
     "legendFormat": "Used Disk Space"
    }
   ]
  },
  {
   "title": "Available Memory on Node",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "Available Memory" },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "Unavailable Memory"
    }
   ]
  },
  {
   "title": "Disk I/O on Node",
   "type": "graph",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total[$interval])) by (device)",
     "legendFormat": "READ /{{device}}"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total[$interval])) by (device)",
     "legendFormat": "WRITE /{{device}}"
    }
   ]
  },
  {
   "title": "System Load on Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"^node_load.*\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Network Traffic on Node",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{id=~\"/docker\"}[$interval]))",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{id=~\"/docker\"}[$interval]))",
     "legendFormat": "SENT"
    }
   ]
  },
  {
   "title": "CPU Usage per Container (Stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (label_replace(rate(container_cpu_usage_seconds_total{id=~\"/docker/[a-f0-9]+\"}[$interval]), \"name\", \"$1\", \"id\", \"/docker/([a-f0-9]{12}).*\")) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Container (Stacked)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (label_replace(container_memory_rss{id=~\"/docker/[a-f0-9]+\"}, \"name\", \"$1\", \"id\", \"/docker/([a-f0-9]{12}).*\"))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (label_replace(rate(container_network_transmit_bytes_total{id=~\"/docker/[a-f0-9]+\"}[$interval]), \"name\", \"$1\", \"id\", \"/docker/([a-f0-9]{12}).*\"))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Cached Memory per Container (Stacked)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (label_replace(container_memory_cache{id=~\"/docker/[a-f0-9]+\"}, \"name\", \"$1\", \"id\", \"/docker/([a-f0-9]{12}).*\"))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (label_replace(rate(container_network_receive_bytes_total{id=~\"/docker/[a-f0-9]+\"}[$interval]), \"name\", \"$1\", \"id\", \"/docker/([a-f0-9]{12}).*\"))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Version Info",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "cadvisor_version_info",
     "legendFormat": "cAdvisor Version: {{cadvisorVersion}}"
    },
    {
     "expr": "prometheus_build_info",
     "legendFormat": "Prometheus Version: {{version}}"
    },
    {
     "expr": "node_exporter_build_info",
     "legendFormat": "Node-Exporter Version: {{version}}"
    },
    {
     "expr": "cadvisor_version_info",
     "legendFormat": "Docker Version: {{dockerVersion}}"
    },
    { "expr": "cadvisor_version_info", "legendFormat": "Host OS Version: {{osVersion}}" },
    {
     "expr": "cadvisor_version_info",
     "legendFormat": "Host Kernel Version: {{kernelVersion}}"
    }
   ]
  }
 ]
}